"""add email to users and amount/date to billing_records

Revision ID: 920040829c67
Revises: cbd39a350100
Create Date: 2026-03-05 08:03:42.677063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920040829c67'
down_revision: Union[str, Sequence[str], None] = 'cbd39a350100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_records', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('billing_records', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.drop_column('billing_records', 'date')
    op.drop_column('billing_records', 'amount')
    # ### end Alembic commands ###
