"""add_ml_fields_to_patient_and_billing

Revision ID: e24e366a2879
Revises: fb64ea4acf9f
Create Date: 2026-03-11 05:42:26.113063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e24e366a2879'
down_revision: Union[str, Sequence[str], None] = 'fb64ea4acf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_records', sa.Column('diagnosis_code', sa.String(), nullable=True))
    op.add_column('billing_records', sa.Column('anomaly_score', sa.Float(), nullable=True))
    op.add_column('billing_records', sa.Column('is_flagged', sa.Boolean(), nullable=True))
    op.add_column('patients', sa.Column('insurance_type', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('email', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('phone', sa.String(), nullable=True))
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.drop_column('patients', 'phone')
    op.drop_column('patients', 'email')
    op.drop_column('patients', 'insurance_type')
    op.drop_column('billing_records', 'is_flagged')
    op.drop_column('billing_records', 'anomaly_score')
    op.drop_column('billing_records', 'diagnosis_code')
    # ### end Alembic commands ###
